# If enabled, this workflow will be triggered after the 'publish' job in the build workflow (ci.yml) has finished

name: Post-Publish Workflow

on:
#  workflow_call:
  pull_request:
    branches: 
      - main
      
jobs:
  post_publish:
    runs-on: ubuntu-latest
    name: Post-Publish Job
    steps:
      - run: echo 'Replace with custom steps'
      #
      - name: Checkout code
        uses: actions/checkout@v2
      #
      - name: Aqua code scanning(SCA,IaC and SAST)
        uses: docker://aquasec/aqua-scanner
        with:
          args: trivy fs --security-checks config,vuln,secret --sast .
          # To customize which severities to scan for, add the following flag: --severity UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
          # To enable SAST scanning, add: --sast
          # To enable npm/dotnet non-lock file scanning, add: --package-json / --dotnet-proj
        env:
          AQUA_KEY: ${{ secrets.AQUA_KEY }}
          AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
          GITHUB_TOKEN: ${{ github.token }}
          TRIVY_RUN_AS_PLUGIN: 'aqua'      
      
